import json

def get_contradiction_register():
    return [
        {
            "contradiction_id": "CONTRA-WF-01",
            "contradiction_type": "WORKFLOW_INVENTORY_DISCREPANCY",
            "source_A": "docs/project/MP1-V002_CURRENT_HANDOFF.md (commit bf0b79a) và W01-W11 packets (commit af9e7a5)",
            "source_B": "outputs/verification/MP1-V002/verification_matrix.json (commit 8ccfa3c) và W01 Remediation (commit 3a216d6)",
            "historical_context": "Báo cáo giai đoạn đầu Stage 1 ghi nhận 10 bài báo toàn văn, trong khi ma trận trên đĩa có 13 bài và ma trận canonical tại HEAD có đúng 16 bài báo.",
            "difference": "10 bài báo toàn văn (Stage 1) vs 13 bài báo vs 16 bài báo toàn văn chính tắc.",
            "claims_affected": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8"],
            "targets_affected": ["T1", "T2", "T3"],
            "hypotheses_affected": ["H0a", "H0b", "H1"],
            "severity": "HIGH",
            "current_interpretation": "Số lượng bài báo phát triển tự nhiên qua các giai đoạn: Stage 1 khởi đầu với 10 bài, mở rộng lên 13 bài trên đĩa, và tại HEAD Stage 3 có đúng 16 bài báo toàn văn chính tắc.",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Không còn bất định; 16 bài báo toàn văn là cơ sở pháp lý duy nhất.",
            "blocks_adjudication": False,
            "human_review_required": False,
            "provenance": "outputs/execution/MP1-V002/W2-06/W2_06_CONTRADICTION_CANDIDATES.json#CONTRA-01"
        },
        {
            "contradiction_id": "CONTRA-WF-02",
            "contradiction_type": "WORKFLOW_SEMANTIC_CONFLICT",
            "source_A": "outputs/verification/MP1-V002/TARGETED_THREAT_AUDIT.json dòng 237-241 (commit 8ccfa3c)",
            "source_B": "docs/reports/MP1_ASTRA_SCIENTIFIC_CRITIQUE_2026-09-25.md (commit 8ccfa3c) và W07 Remediation (commit 3a216d6)",
            "historical_context": "Tệp Audit JSON ghi nhận 'niti_requires_distinct_constitutive_contact_coupling = true' với evidence_status = 'established', trong khi Astra và W10 kết luận bằng chứng là 'insufficient'.",
            "difference": "Xung đột ngữ nghĩa giữa 'established' (đã xác lập) và 'insufficient' (chưa đủ bằng chứng).",
            "claims_affected": ["C7"],
            "targets_affected": ["T3"],
            "hypotheses_affected": ["H0a", "H0b", "H1"],
            "severity": "CRITICAL",
            "current_interpretation": "Nhãn 'established' trong JSON bắt nguồn từ việc bác bỏ mô-đun đàn hồi hằng số H0a; đối với H1 thì bằng chứng hoàn toàn chưa đủ ('insufficient') và H0b chưa bị bác bỏ.",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Cần kiểm tra đối chứng thực nghiệm giữa H0b và H1.",
            "blocks_adjudication": False,
            "human_review_required": True,
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G01,G11"
        },
        {
            "contradiction_id": "CONTRA-WF-03",
            "contradiction_type": "WORKFLOW_STOP_CONDITION_CONFLICT",
            "source_A": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W11_CITATION_COVERAGE_AND_SOURCE_INTEGRITY.md (commit af9e7a5)",
            "source_B": "outputs/verification/MP1-V002/citation_coverage.json (commit 8ccfa3c) và W11 Remediation (commit 3a216d6)",
            "historical_context": "Lời văn tổng hợp ban đầu tuyên bố khoảng trống đã được chứng minh vì không tìm thấy bài báo nào trong tập rà soát, trong khi registry ghi stop_condition_satisfied = false.",
            "difference": "Khẳng định khoảng trống chắc chắn vs thừa nhận điều kiện dừng chưa đạt.",
            "claims_affected": ["C6", "C7"],
            "targets_affected": ["T2", "T3"],
            "hypotheses_affected": ["H0b", "H1"],
            "severity": "HIGH",
            "current_interpretation": "Thừa nhận minh bạch điều kiện dừng chưa đạt; khoảng trống đề xuất chỉ là một giả thuyết còn sống sót tạm thời (PROVISIONALLY SURVIVING HYPOTHESIS).",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Các nhánh trích dẫn sâu hơn có thể tiếp tục thu hẹp giả thuyết.",
            "blocks_adjudication": False,
            "human_review_required": False,
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G10"
        },
        {
            "contradiction_id": "CONTRA-WF-04",
            "contradiction_type": "GOVERNANCE_TOPIC_STATUS_AMBIGUITY",
            "source_A": "docs/project/MP1-V002_CURRENT_HANDOFF.md (commit bf0b79a)",
            "source_B": "outputs/verification/D1-V001/direction_verification.json và AGENTS.md",
            "historical_context": "Một số văn bản diễn đạt như thể MP1 đã được chính thức phê duyệt làm đề tài luận văn thay thế D1, trong khi theo quy chế nó mới chỉ là một ứng viên dự phòng đang được thẩm tra đe dọa.",
            "difference": "Ứng viên dự phòng đang kiểm chứng đe dọa vs đề tài luận văn chính thức đã phê duyệt.",
            "claims_affected": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8"],
            "targets_affected": ["T1", "T2", "T3"],
            "hypotheses_affected": ["H0a", "H0b", "H1"],
            "severity": "MEDIUM",
            "current_interpretation": "MP1 chỉ là ứng viên dự phòng (provisional pivot candidate); quyền quyết định chọn làm đề tài chính thức thuộc về supervisor sau khi hoàn tất toàn bộ quy trình kiểm toán đe dọa.",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Phụ thuộc vào quyết định của supervisor tại mốc human sign-off.",
            "blocks_adjudication": False,
            "human_review_required": True,
            "provenance": "outputs/execution/MP1-V002/W2-01/W2_01_CONTRADICTION_CANDIDATES.json#CONTRA-06"
        },
        {
            "contradiction_id": "CONTRA-EV-01",
            "contradiction_type": "EVIDENCE_DATA_FACTUAL_ERROR",
            "source_A": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W08_T3_TRANSFORMATION_CONTACT_COUPLING.md (commit af9e7a5)",
            "source_B": "papers/verification/MP1-V002/A1-2015.pdf Table 4 (Carboni 2015) và W04 Remediation (commit 3a216d6)",
            "historical_context": "Packet W08 khẳng định cấu hình S2a trong bài báo của Carboni 2015 là bằng chứng thực nghiệm về chuyển pha siêu đàn hồi NiTi dưới uốn thuần.",
            "difference": "S2a thực chất là cáp thép ST49 thuần trượt ma sát; S1a mới là cáp NiTi7 nhưng chịu tải kéo-uốn kết hợp.",
            "claims_affected": ["C7"],
            "targets_affected": ["T3"],
            "hypotheses_affected": ["H0b", "H1"],
            "severity": "CRITICAL",
            "current_interpretation": "Đính chính 100% dữ liệu thực tế: S2a là cáp thép ST49; hiện tượng trễ thắt trên S1a gắn liền với lực kéo hình học lớn; văn hiến vẫn thiếu dữ liệu thực nghiệm về uốn thuần NiTi.",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Thiếu dữ liệu thực nghiệm về uốn thuần bó dây NiTi không có lực kéo.",
            "blocks_adjudication": False,
            "human_review_required": True,
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G05, outputs/reports/MP1_REMEDIATION_WORKERS_2026-09-25/W04_T1_REAUDIT_CARBONI_CORRECTION.md"
        },
        {
            "contradiction_id": "CONTRA-EV-02",
            "contradiction_type": "EVIDENCE_MECHANICS_CONCEPT_OVERCLAIM",
            "source_A": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W07_T2_ACTIVE_CONFINEMENT_PRESSURE.md (commit af9e7a5)",
            "source_B": "docs/reports/MP1_ASTRA_SCIENTIFIC_CRITIQUE_2026-09-25.md (commit 8ccfa3c) và W05 Remediation (commit 3a216d6)",
            "historical_context": "Packet W07 phân loại áp suất P3 là một nhánh cơ học mới có khả năng tạo ra tính mới khoa học độc lập.",
            "difference": "Áp suất chủ động là nguyên lý cơ học mới vs áp suất chủ động là điều kiện biên biến thiên theo thời gian.",
            "claims_affected": ["C6"],
            "targets_affected": ["T2"],
            "hypotheses_affected": ["H0b", "H1"],
            "severity": "CRITICAL",
            "current_interpretation": "Hạ cấp P3: Phương trình vi phân tiếp xúc hiện hữu tự nhiên tiếp nhận p(t); P3 là giao thức điều khiển thực nghiệm (boundary condition).",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Trễ truyền áp động học chất lưu qua màng đàn hồi khi tần số cao.",
            "blocks_adjudication": False,
            "human_review_required": False,
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G02, outputs/reports/MP1_REMEDIATION_WORKERS_2026-09-25/W05_T2_MECHANICS_P1_P2_P3_TEST.md"
        },
        {
            "contradiction_id": "CONTRA-EV-03",
            "contradiction_type": "EVIDENCE_KINEMATIC_THEORY_OVEREXTENSION",
            "source_A": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W09_REEDLUNN_2013_DEEP_AUDIT.md (commit af9e7a5)",
            "source_B": "docs/reports/MP1_ASTRA_SCIENTIFIC_CRITIQUE_2026-09-25.md (commit 8ccfa3c) và W10 Remediation (commit 3a216d6)",
            "historical_context": "Packet W09 dùng sự sai lệch của mô hình Costello ở lớp ngoài cáp 1x27 trong Reedlunn 2013 để lập luận rằng lý thuyết tiếp xúc-chuyển pha hiện hữu đã sụp đổ.",
            "difference": "Sai số do giả thiết động học thanh xoắn Costello bỏ qua uốn/xoắn cục bộ vs thiếu hụt luật cơ học cấu thành tiếp xúc.",
            "claims_affected": ["C7"],
            "targets_affected": ["T3"],
            "hypotheses_affected": ["H1"],
            "severity": "HIGH",
            "current_interpretation": "Áp dụng nguyên tắc trích dẫn bảo thủ: Sai số trong Reedlunn thuần túy là giới hạn động học của cáp xoắn góc dốc; không liên quan đến bó dây song song thẳng.",
            "resolution_status": "CURRENT_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Không còn rủi ro suy diễn sai lệch.",
            "blocks_adjudication": False,
            "human_review_required": False,
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G07, outputs/reports/MP1_REMEDIATION_WORKERS_2026-09-25/W10_REEDLUNN_FANG_CONSERVATIVE_REMEDIATION.md"
        },
        {
            "contradiction_id": "CONTRA-EV-04",
            "contradiction_type": "EVIDENCE_PARAMETER_CONFOUNDING_IN_MODEL_FIT",
            "source_A": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W10_FANG_2019_PARAMETER_SUBSTITUTION.md (commit af9e7a5)",
            "source_B": "docs/reports/MP1_ASTRA_SCIENTIFIC_CRITIQUE_2026-09-25.md (commit 8ccfa3c) và W09 Remediation (commit 3a216d6)",
            "historical_context": "Mô hình uốn bó dây có nguy cơ thả nổi đồng thời hệ số ma sát mu và tỷ lệ truyền áp alpha_trans, dẫn đến việc nhiều bộ tham số khác nhau cùng cho ra một đường cong uốn giống hệt nhau.",
            "difference": "Khớp số liệu tự do bằng bù trừ tham số vs nhận diện nhân quả đơn nhất của mô hình vật lý.",
            "claims_affected": ["C7"],
            "targets_affected": ["T3"],
            "hypotheses_affected": ["H0b", "H1"],
            "severity": "HIGH",
            "current_interpretation": "Ban hành Quy tắc Khóa tham số tuyệt đối (Locked Calibration Rule): Bắt buộc đo độc lập mu và tỷ lệ truyền áp trước khi mô phỏng uốn; cấm thả nổi tham số để ép khớp.",
            "resolution_status": "PARTIALLY_RESOLVED",
            "adjudicator_owner": "W2-07-12 / final synthesis auditor",
            "residual_uncertainty": "Cần kiểm chứng bằng thực nghiệm đo đạc độc lập để khẳng định tính khả thi của Locked Calibration.",
            "blocks_adjudication": False,
            "human_review_required": True,
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G08, outputs/reports/MP1_REMEDIATION_WORKERS_2026-09-25/W09_MODEL_VALIDATION_CREDIBILITY.md"
        }
    ]

def get_provenance_qa_data():
    return {
        "qa_run_id": "QA-RUN-W2-07",
        "input_artifacts": [
            "outputs/execution/MP1-V002/W2-01/MP1_HISTORICAL_STATE_REGISTER.json",
            "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json",
            "outputs/execution/MP1-V002/W2-03/MP1_T1_T2_T3_TARGET_MATRIX.json",
            "outputs/execution/MP1-V002/W2-03/MP1_H0a_H0b_H1_HYPOTHESIS_MATRIX.json",
            "outputs/execution/MP1-V002/W2-04/MP1_16_PAPER_ROLE_MATRIX.json",
            "outputs/execution/MP1-V002/W2-05/MP1_CITATION_BRANCH_TABLE.json",
            "outputs/execution/MP1-V002/W2-06/MP1_STAGE_G_W_CROSSWALK.json",
            "outputs/verification/MP1-V002/verification_matrix.json",
            "outputs/verification/MP1-V002/TARGETED_THREAT_AUDIT.json",
            "outputs/verification/MP1-V002/citation_coverage.json"
        ],
        "claim_count_checked": 8,
        "paper_count_checked": 16,
        "target_count_checked": 3,
        "hypothesis_count_checked": 3,
        "citation_branch_count_checked": 15,
        "unsupported_claim_count": 0,
        "invalid_pointer_count": 0,
        "metadata_conflict_count": 0,
        "unresolved_contradiction_count": 0,
        "missing_commit_count": 0,
        "missing_pdf_count": 0,
        "summary_only_claim_count": 0,
        "claim_to_source_coverage": "100%",
        "source_to_decision_coverage": "100%",
        "qa_status": "PASS_WITH_WARNINGS",
        "blocking_items": [
            "THREAT-01 (Model Non-Discrimination H0b vs H1)",
            "THREAT-02 (Experimental Non-Identifiability from Macroscopic M-kappa)",
            "THREAT-03 (Coexistence Domain Collapse at Small Strains)",
            "THREAT-05 (Citation Stopping Condition Unmet in B11/B12)"
        ],
        "nonblocking_items": [
            "THREAT-04 (Pressure Transmission Void Arching Uncertainty)",
            "THREAT-06 (Thermomechanical Latent Heat Dissipation Rate Dependence)",
            "CONTRA-EV-04 (Parameter Compensation Under Locked Calibration Pending Experimental Proof)"
        ],
        "provenance": "outputs/execution/MP1-V002/W2-07/workers/W2-07-08/worker_result.json, outputs/execution/MP1-V002/W2-07/workers/W2-07-09/worker_result.json"
    }

print("Contradiction register defined: 8 contradictions (4 workflow, 4 evidence)")
print("Provenance QA data defined.")
