import json

def get_non_novelty_register():
    return [
        {
            "non_novelty_id": "NN-01",
            "claim_id": "C1",
            "non_novelty_category": "DEVICE_LEVEL_PRIOR_ART",
            "claim_before": "Cơ chế biến đổi độ cứng bằng kẹt dây (wire jamming) cho robot mềm dưới áp suất giam giữ.",
            "claim_after": "ĐÃ ĐÓNG (CLOSED). Hiện tượng kẹt ma sát giữa các sợi dây trong dầm dẻo là văn hiến đã xác lập trong robot mềm.",
            "prior_art_source": "Bai et al. (2022) / Zhang & Yao (2026)",
            "paper_id": "240fbf6022",
            "paper_title": "A Wire Jamming-Based Variable Stiffness Soft Gripper",
            "authors": "Bai, Y. et al.",
            "year": 2022,
            "DOI": "10.1109/LRA.2022.3188880",
            "what_source_proves": "Chứng minh biến thiên độ cứng lên tới 15 lần nhờ kẹt ma sát bó dây thép trong ngón tay robot mềm; Zhang & Yao 2026 mô hình hóa dầm sợi dẻo có trượt ma sát Coulomb.",
            "what_source_does_not_prove": "Không nghiên cứu vật liệu siêu đàn hồi NiTi có chuyển pha ứng suất (chỉ dùng thép đàn hồi tuyến tính và sợi nylon).",
            "impact_on_MP1": "Khẳng định cấp thiết bị về wire jamming hoàn toàn không có tính mới; bị loại bỏ 100% khỏi phạm vi đóng góp của luận văn.",
            "evidence_status": "closed_by_full_text",
            "confidence": "high",
            "provenance": "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json#C1, outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W02_C1_C2_EVIDENCE.md"
        },
        {
            "non_novelty_id": "NN-02",
            "claim_id": "C2",
            "non_novelty_category": "DEVICE_LEVEL_PRIOR_ART",
            "claim_before": "Cơ cấu kẹt dưới áp suất dương (positive-pressure jamming) dùng chất lưu hoặc khí nén.",
            "claim_after": "ĐÃ ĐÓNG (CLOSED). Cơ cấu kẹt ép bằng áp suất dương trong màng bao đàn hồi đã được công bố và ứng dụng rộng rãi.",
            "prior_art_source": "Liu et al. (2021) / Zhang & Yao (2026)",
            "paper_id": "182d854610",
            "paper_title": "A Positive Pressure Jamming Based Variable Stiffness Structure and its Application on Wearable Robots",
            "authors": "Liu, X. et al.",
            "year": 2021,
            "DOI": "10.1109/LRA.2021.3097255",
            "what_source_proves": "Chứng minh áp suất dương lên tới 250 kPa trong đồ gá đeo giúp tăng độ cứng vượt trội và tránh hiện tượng nhăn màng của chân không.",
            "what_source_does_not_prove": "Không nghiên cứu bó dây NiTi và không khảo sát phương trình vi phân tiếp xúc có áp suất biến thiên chủ động theo thời gian.",
            "impact_on_MP1": "Áp suất dương không phải là nguyên lý mới; không thể dựa vào áp suất dương để biện minh tính mới cho đề tài.",
            "evidence_status": "closed_by_full_text",
            "confidence": "high",
            "provenance": "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json#C2, outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W02_C1_C2_EVIDENCE.md"
        },
        {
            "non_novelty_id": "NN-03",
            "claim_id": "C3",
            "non_novelty_category": "DEVICE_LEVEL_PRIOR_ART",
            "claim_before": "Sự kết hợp giữa hợp kim nhớ hình (SMA) và cơ cấu kẹt hạt/lớp (jamming) trong cùng một cơ cấu.",
            "claim_after": "ĐÓN ĐẦU THỰC CHẤT (SUBSTANTIALLY_PREEMPTED). Dòng nghiên cứu của Takashima và Matsumoto đã kết hợp sâu rộng SMA và jamming.",
            "prior_art_source": "Takashima et al. (2022, 2024) / Matsumoto et al. (2024)",
            "paper_id": "2cd907e77a",
            "paper_title": "Variable Stiffness Device Using Shape Memory Alloy and Granular Jamming",
            "authors": "Takashima, K. et al.",
            "year": 2022,
            "DOI": "10.1109/LRA.2022.3144502",
            "what_source_proves": "Tích hợp dây kích hoạt nhiệt SMA trong hạt jamming chân không để điều khiển độ cứng và khóa hình dạng.",
            "what_source_does_not_prove": "Dùng SMA làm actuator nhiệt hoặc cốt nâng đỡ, không khảo sát bó dây NiTi siêu đàn hồi tự trượt ma sát tiếp xúc với nhau.",
            "impact_on_MP1": "Khẳng định phối hợp kiến trúc lai SMA + jamming bị đón đầu ở cấp hệ thống; chỉ bài toán cơ học trượt nội tại NiTi là có thể xem xét.",
            "evidence_status": "substantially_preempted",
            "confidence": "high",
            "provenance": "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json#C3, outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W03_C3_SMA_JAMMING_LINEAGE.md"
        },
        {
            "non_novelty_id": "NN-04",
            "claim_id": "C4",
            "non_novelty_category": "IMPLEMENTATION_SUBSTITUTION",
            "claim_before": "Tích hợp nguồn áp suất thu nhỏ trên thân robot mềm để điều khiển cơ cấu kẹt độc lập.",
            "claim_after": "ĐÃ ĐÓNG / ĐÓN ĐẦU THỰC CHẤT. Các loại bơm vi mô tích hợp (ECF, nhiệt, điện môi, SMA) đã được công bố dày đặc.",
            "prior_art_source": "Huynh et al. (2022) / Wang et al. (2024)",
            "paper_id": "bbe88a0c04",
            "paper_title": "Electroconjugate Fluid Micropump for Soft Actuators",
            "authors": "Huynh, T. et al.",
            "year": 2022,
            "DOI": "10.1109/TMECH.2022.3168890",
            "what_source_proves": "Khả năng tích hợp trọn gói bơm vi mô áp suất cao trên thân cơ cấu chấp hành mềm quy mô milimét.",
            "what_source_does_not_prove": "Không đóng góp cơ học về tiếp xúc ma sát hay chuyển pha vật liệu.",
            "impact_on_MP1": "Tích hợp bơm vi mô thuần túy là giải pháp kỹ thuật chế tạo, không có giá trị tính mới khoa học cơ học.",
            "evidence_status": "closed_by_full_text",
            "confidence": "high",
            "provenance": "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json#C4, outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W04_C4_C8_PRESSURE_SOURCE_EVIDENCE.md"
        },
        {
            "non_novelty_id": "NN-05",
            "claim_id": "C5",
            "non_novelty_category": "EXISTENCE_LEVEL_PRIOR_ART",
            "claim_before": "Cơ học tiếp xúc và ma sát trượt giữa các dây NiTi siêu đàn hồi.",
            "claim_after": "ĐÃ ĐÓNG (CLOSED). Cơ học tiếp xúc đường Hertz và ma sát trượt Coulomb giữa các sợi NiTi đã được mô hình hóa và đo đạc đầy đủ.",
            "prior_art_source": "Carboni et al. (2015) / Vahidi et al. (2022) / Silva et al. (2020)",
            "paper_id": "53200aa0c6",
            "paper_title": "Finite Element Modeling and Hysteresis Simulation of NiTi Wire Ropes",
            "authors": "Vahidi, M. et al.",
            "year": 2022,
            "DOI": "10.1007/s11071-022-07450-4",
            "what_source_proves": "Mô phỏng 3D phần tử hữu hạn Abaqus UMAT có ma sát Coulomb và tiếp xúc phạt (penalty) giữa các dây NiTi; đo hệ số ma sát mu = 0.18 - 0.22.",
            "what_source_does_not_prove": "Không khảo sát bó dây thẳng song song chịu trường áp suất phân bố biến thiên chủ động theo thời gian.",
            "impact_on_MP1": "Mục tiêu T1 chính thức đóng bằng toàn văn; không thể tuyên bố tính mới về hiện tượng ma sát dây NiTi độc lập.",
            "evidence_status": "closed_by_full_text",
            "confidence": "high",
            "provenance": "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json#C5, outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W06_T1_NITI_CONTACT_FRICTION.md"
        },
        {
            "non_novelty_id": "NN-06",
            "claim_id": "C6",
            "non_novelty_category": "BOUNDARY_CONDITION_NOVELTY",
            "claim_before": "Áp suất giam giữ chủ động biến thiên p(t) tạo ra một nhánh quy luật cơ học tiếp xúc mới (P3).",
            "claim_after": "HẠ CẤP THÀNH ĐIỀU KIỆN BIÊN (DOWNGRADED). p(t) chỉ là điều kiện biên thay đổi theo thời gian; phương trình tiếp xúc hiện hữu tiếp nhận tự nhiên.",
            "prior_art_source": "Tjahjanto et al. (2017) / Xin Liu (2004) / Astra Critique G02",
            "paper_id": "ccdc1bb980",
            "paper_title": "Submarine Cable Bending Mechanics Under External Hydrostatic Pressure",
            "authors": "Tjahjanto, P. et al.",
            "year": 2017,
            "DOI": "10.1016/j.oceaneng.2017.06.012",
            "what_source_proves": "Phương trình vi phân tiếp xúc dầm cáp dq/dx = -mu * fn(p) giải tích và số tự nhiên tiếp nhận lịch sử tải và áp suất bất kỳ mà không cần đổi công thức cơ học.",
            "what_source_does_not_prove": "Các nghiên cứu trước tập trung vào áp suất thủy tĩnh tĩnh (P2) hoặc lực căng tự thân (P1), chưa áp dụng cho tay gắp mềm.",
            "impact_on_MP1": "P3 bị tước bỏ tư cách nguyên lý cơ học mới; chỉ được xem như giao thức điều khiển thực nghiệm (control protocol).",
            "evidence_status": "downgraded_to_boundary_condition",
            "confidence": "high",
            "provenance": "docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G02, outputs/reports/MP1_REMEDIATION_WORKERS_2026-09-25/W05_T2_MECHANICS_P1_P2_P3_TEST.md"
        },
        {
            "non_novelty_id": "NN-07",
            "claim_id": "C7",
            "non_novelty_category": "MODEL_DISCRIMINATION_QUESTION",
            "claim_before": "Ghép cặp chuyển pha siêu đàn hồi và ma sát trượt là một khoảng trống cơ học hoàn toàn chưa từng được mô hình hóa.",
            "claim_after": "ĐÓN ĐẦU THỰC CHẤT TRONG CÁP DÂY / THU HẸP NGHIÊM NGẶT. Các mô hình vĩ mô (Fang 2019, Carboni 2016) đã mô tả trễ thắt và ma sát.",
            "prior_art_source": "Fang et al. (2019) / Carboni et al. (2016) / Niu et al. (2021)",
            "paper_id": "2f7fcf2f8f",
            "paper_title": "A Phenomenological Constitutive Model for Superelastic SMA Cables Under Cyclic Tension",
            "authors": "Fang, C. et al.",
            "year": 2019,
            "DOI": "10.1016/j.engstruct.2019.109356",
            "what_source_proves": "Mô hình sợi OpenSees tái hiện xuất sắc trễ dạng cờ và suy giảm chu kỳ bằng hàm hiện tượng học mà không cần giải phương trình tiếp xúc vi mô.",
            "what_source_does_not_prove": "Không chứng minh cơ chế vi mô nhân quả trong bó dây chịu nén ngang; bỏ qua ma sát tiếp xúc cục bộ từng điểm.",
            "impact_on_MP1": "Khẳng định C7 bị thu hẹp thành bài toán phân biệt mô hình (H0b vs H1) trong Miền Cùng Tồn Tại; không tồn tại tính mới phổ quát.",
            "evidence_status": "substantially_preempted_and_narrowed",
            "confidence": "high",
            "provenance": "outputs/reports/MP1_REMEDIATION_WORKERS_2026-09-25/W07_PARAMETER_SUBSTITUTION_H0_H1.md, docs/reports/MP1_ASTRA_CRITIQUE_REMEDIATION_2026-09-25.md#G01"
        },
        {
            "non_novelty_id": "NN-08",
            "claim_id": "C8",
            "non_novelty_category": "IMPLEMENTATION_SUBSTITUTION",
            "claim_before": "Cơ cấu piston/bơm vi mô kích hoạt bằng dây SMA là một phát minh cơ cấu mới cho robot biến đổi độ cứng.",
            "claim_after": "ĐÃ ĐÓNG (CLOSED). Cơ cấu bơm piston/màng bằng dây SMA đã có tiền nhiệm đầy đủ trong y sinh và vi cơ điện tử.",
            "prior_art_source": "Kotb et al. (2021) / Pierce et al. (2013)",
            "paper_id": "55457a97c6",
            "paper_title": "Shape Memory Alloy Capsule Micropump for Drug Delivery Applications",
            "authors": "Kotb, M. et al.",
            "year": 2021,
            "DOI": "10.3390/mi12050520",
            "what_source_proves": "Bơm vi mô viên nang dẫn động bằng lò xo và dây SMA đạt áp suất và lưu lượng ổn định.",
            "what_source_does_not_prove": "Không liên quan đến cơ học dầm biến đổi độ cứng.",
            "impact_on_MP1": "C8 chỉ là thay thế cơ cấu chấp hành (actuator substitution); bị loại bỏ hoàn toàn để bảo vệ độ tin cậy của luận văn.",
            "evidence_status": "closed_by_full_text",
            "confidence": "high",
            "provenance": "outputs/execution/MP1-V002/W2-02/MP1_C1_C8_CLAIM_MATRIX.json#C8, outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W04_C4_C8_PRESSURE_SOURCE_EVIDENCE.md"
        }
    ]

print("Non-novelty register defined: 8 claims (C1–C8)")
