import json

def get_stage1_packets():
    return [
        {
            "packet_id": "W01",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W01_ORIGINAL_ARCHITECTURE_AND_V001_DECISION.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Tái dựng kiến trúc thiết bị ban đầu từ đề xuất của mentor, phân tích nguyên nhân sụp đổ tính mới ở cấp độ linh kiện trong MP1-V001, và xác định tiền đề chuyển dịch sang mechanics core.",
            "claims_affected": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8"],
            "targets_affected": ["T1", "T2"],
            "hypotheses_affected": ["H0a"],
            "papers_used": ["240fbf6022", "182d854610", "3aa8790db0", "2cd907e77a", "bbe88a0c04", "c6a31066f8", "de64029540", "55457a97c6"],
            "method_or_model": "Phân tích cấu trúc hệ thống (subsystem functional decomposition) chia tách cơ cấu jamming, vật liệu thông minh, nguồn áp suất tích hợp và cơ cấu bơm vi mô.",
            "experiment_discussed": "Đối soát các hệ thống robot mềm và cơ cấu thay đổi độ cứng thực nghiệm trong y sinh và robot đeo (exoskeletons).",
            "verified_conclusions": "Sự kết hợp linh kiện cấp thiết bị (wire jamming + SMA + micropump tích hợp) hoàn toàn không có tính mới khoa học; bị tiền nhiệm bởi hàng loạt nghiên cứu từ 2013-2024.",
            "inferred_conclusions": "Hướng nghiên cứu duy nhất có thể bảo vệ được là đi sâu vào cơ học bản chất (friction, phase transformation, variable normal pressure) thay vì phối hợp linh kiện.",
            "unresolved_issues": "Chưa làm rõ ranh giới giữa việc sụp đổ tính mới linh kiện và việc phát biểu một bài toán cơ học tiếp xúc mới thực sự.",
            "later_critique_ids": ["G01", "G02"],
            "later_remediation_ids": ["W02", "W03"],
            "superseded_interpretation": "Từng kỳ vọng việc tích hợp bơm vi mô SMA với cơ cấu jamming dây tạo nên một hệ thống robot mềm mới toàn diện.",
            "corrected_interpretation": "Toàn bộ cấu trúc thiết bị C1-C4 và C8 đã bị đóng; chỉ chuyển dịch sang nghiên cứu lõi cơ học (C5-C7, T1-T3) với tư cách một giả thuyết cơ học.",
            "evidence_status": "established",
            "confidence": "high",
            "provenance": "W01_ORIGINAL_ARCHITECTURE_AND_V001_DECISION.md#L1-L286"
        },
        {
            "packet_id": "W02",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W02_C1_C2_EVIDENCE.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra toàn diện tính mới của cơ chế wire jamming (C1) và positive-pressure jamming (C2) trong robot mềm.",
            "claims_affected": ["C1", "C2"],
            "targets_affected": [],
            "hypotheses_affected": ["H0a"],
            "papers_used": ["240fbf6022", "182d854610", "3aa8790db0"],
            "method_or_model": "Mô hình dầm Euler-Bernoulli có trượt ma sát Coulomb giữa các sợi; mô hình nén dương màng đàn hồi.",
            "experiment_discussed": "Thử nghiệm uốn 3 điểm trên dầm dây thép và dầm sợi nylon chịu áp suất dương từ 0 đến 250 kPa; đo lực uốn vĩ mô.",
            "verified_conclusions": "C1 và C2 hoàn toàn bị đóng (closed by full text). Bai et al. 2022 chứng minh thay đổi độ cứng 15 lần với bó dây thép; Liu et al. 2021 dùng áp suất dương trong đồ gá đeo; Zhang & Yao 2026 lập mô hình sợi nylon chi tiết.",
            "inferred_conclusions": "Mô hình sợi đàn hồi của Zhang & Yao 2026 có thể được mở rộng sang sợi siêu đàn hồi NiTi hay không là một câu hỏi mở.",
            "unresolved_issues": "Khả năng mô hình đàn hồi hiện có mở rộng sang vật liệu có biến dạng phi tuyến và biến đổi pha.",
            "later_critique_ids": ["G01", "G02"],
            "later_remediation_ids": ["W02"],
            "superseded_interpretation": "Cho rằng wire jamming dưới áp suất dương là một nguyên lý hoạt động mới mẻ chưa được mô hình hóa.",
            "corrected_interpretation": "C1 và C2 đóng 100%; không được phép đưa vào novelty claim của luận văn.",
            "evidence_status": "established",
            "confidence": "high",
            "provenance": "W02_C1_C2_EVIDENCE.md#L1-L261"
        },
        {
            "packet_id": "W03",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W03_C3_SMA_JAMMING_LINEAGE.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Kiểm chứng chuyên sâu dòng nghiên cứu tích hợp SMA và Jamming (C3) của nhóm Takashima (2022-2024) và Matsumoto (2024).",
            "claims_affected": ["C3"],
            "targets_affected": ["T1"],
            "hypotheses_affected": ["H0a"],
            "papers_used": ["2cd907e77a", "7ce492505d", "99fe24da8b", "d3b3b6963f"],
            "method_or_model": "Kích hoạt nhiệt dây SMA trong môi trường hạt jamming hoặc tấm jamming để điều khiển độ cứng và biến dạng hình học.",
            "experiment_discussed": "Tay gắp mềm biến đổi độ cứng kết hợp dây nhiệt SMA và hạt jamming chân không; cơ cấu ngón tay uốn chủ động.",
            "verified_conclusions": "C3 bị đón đầu thực chất (substantially preempted). Dây SMA được dùng rộng rãi để làm khung trợ lực hoặc kích hoạt biến dạng cho cơ cấu jamming.",
            "inferred_conclusions": "Các công trình của Takashima dùng dây SMA làm actuator nhiệt hoặc cốt nâng đỡ trong hạt, không phải bó dây NiTi tự trượt ma sát với nhau.",
            "unresolved_issues": "Phân biệt rõ ràng giữa cơ cấu SMA phát nhiệt uốn chủ động và cơ cấu bó dây NiTi siêu đàn hồi tự kẹt ma sát thụ động.",
            "later_critique_ids": ["G01", "G03"],
            "later_remediation_ids": ["W02", "W03"],
            "superseded_interpretation": "Cho rằng việc đặt dây SMA vào trong cấu trúc jamming tự nó tạo nên tính mới kiến trúc.",
            "corrected_interpretation": "C3 bị đón đầu ở cấp hệ thống; chỉ có bài toán ma sát trượt nội tại giữa các dây NiTi siêu đàn hồi là có thể còn khác biệt về cơ học.",
            "evidence_status": "established",
            "confidence": "high",
            "provenance": "W03_C3_SMA_JAMMING_LINEAGE.md#L1-L235"
        },
        {
            "packet_id": "W04",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W04_C4_C8_PRESSURE_SOURCE_EVIDENCE.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra nguồn áp suất tích hợp trên thân (C4) và cơ cấu piston/bơm vi mô SMA (C8).",
            "claims_affected": ["C4", "C8"],
            "targets_affected": ["T2"],
            "hypotheses_affected": ["H0a"],
            "papers_used": ["bbe88a0c04", "c6a31066f8", "de64029540", "55457a97c6"],
            "method_or_model": "Bơm vi mô chất lỏng điện liên hợp (ECF), bơm giãn nở nhiệt chất lỏng-khí, và bơm màng/piston dẫn động bằng dây SMA.",
            "experiment_discussed": "Đo áp suất đầu ra và lưu lượng của bơm vi mô tích hợp trong cơ cấu chấp hành mềm và thiết bị phân phối thuốc vi mô.",
            "verified_conclusions": "C4 và C8 hoàn toàn bị đóng / đón đầu thực chất. Bơm vi mô ECF (Huynh 2022), bơm nhiệt vi lưu (Wang 2024), và bơm màng SMA (Pierce 2013, Kotb 2021) đã được phát triển sâu sắc.",
            "inferred_conclusions": "C8 chỉ là sự thay thế cơ cấu chấp hành (actuator substitution), mang rủi ro bị bác bỏ rất cao nếu coi là đóng góp khoa học chính.",
            "unresolved_issues": "Khả năng đáp ứng tần số và tổn hao nhiệt khi tích hợp bơm thu nhỏ vào thân robot mềm.",
            "later_critique_ids": ["G02", "G09"],
            "later_remediation_ids": ["W02", "W03"],
            "superseded_interpretation": "Xem nguồn bơm tích hợp SMA là một trụ cột novel của đề tài luận văn.",
            "corrected_interpretation": "Loại bỏ hoàn toàn C4 và C8 khỏi trọng tâm nghiên cứu; áp suất chỉ được xem như điều kiện biên điều khiển $p(t)$.",
            "evidence_status": "established",
            "confidence": "high",
            "provenance": "W04_C4_C8_PRESSURE_SOURCE_EVIDENCE.md#L1-L299"
        },
        {
            "packet_id": "W05",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W05_C5_C6_C7_V001_BOUNDARY.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Xác định ranh giới thẩm tra của C5, C6, C7 sau MP1-V001 và sự hình thành của Mechanics Core.",
            "claims_affected": ["C5", "C6", "C7"],
            "targets_affected": ["T1", "T2", "T3"],
            "hypotheses_affected": ["H0a", "H1"],
            "papers_used": ["240fbf6022", "182d854610", "2cd907e77a", "c6a31066f8", "3aa8790db0"],
            "method_or_model": "Ma trận giao thoa 3 trục: (1) Siêu đàn hồi/chuyển pha NiTi x (2) Trượt ma sát giữa các dây x (3) Áp suất giam giữ chủ động.",
            "experiment_discussed": "Rà soát toàn bộ 11 bài báo trong tập V001 để tìm xem có bài báo nào giao thoa cả 3 trục hay không.",
            "verified_conclusions": "Trong phạm vi 11 bài báo V001, không có công trình nào chứa cả 3 thành phần này cùng lúc.",
            "inferred_conclusions": "Hình thành đề xuất Mechanics Core dựa trên giao điểm 3 trục này và coi đây là khoảng trống khoa học tiềm năng.",
            "unresolved_issues": "Việc một giao điểm 'mở trong 11 bài báo V001' không đồng nghĩa với việc nó là khoảng trống mở trong toàn bộ nền khoa học cơ học.",
            "later_critique_ids": ["G01", "G02", "G03", "G10"],
            "later_remediation_ids": ["W03", "W05", "W06"],
            "superseded_interpretation": "Nhận định giao điểm 3 trục là novel một cách mặc nhiên chỉ dựa trên ma trận rà soát V001.",
            "corrected_interpretation": "Cần kiểm tra kỹ lưỡng với văn hiến cơ học cáp dây truyền thống (wire rope mechanics) trước khi khẳng định tính mới.",
            "evidence_status": "open_in_corpus_only",
            "confidence": "medium",
            "provenance": "W05_C5_C6_C7_V001_BOUNDARY.md#L1-L160"
        },
        {
            "packet_id": "W06",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W06_T1_NITI_CONTACT_FRICTION.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra chuyên sâu Mục tiêu T1: Cơ học tiếp xúc và ma sát trượt giữa các dây NiTi đã bị tiền nhiệm hay chưa.",
            "claims_affected": ["C5", "C7"],
            "targets_affected": ["T1"],
            "hypotheses_affected": ["H0a"],
            "papers_used": ["d9966f2f5e", "53200aa0c6", "98fee47c04", "e8462758c3", "6dd1ca94d1"],
            "method_or_model": "Mô phỏng phần tử hữu hạn 3D (Abaqus UMAT), luật tiếp xúc ma sát Coulomb/Hertz, mô hình trễ tiếp xúc Bouc-Wen.",
            "experiment_discussed": "Thử nghiệm kéo chu kỳ và uốn chu kỳ trên cáp và tao dây NiTi; đo hệ số ma sát giữa các sợi dây NiTi ($\mu = 0.18 - 0.22$).",
            "verified_conclusions": "Mục tiêu T1 chính thức bị đóng bằng toàn văn (closed by full text). Vahidi 2022 và Carboni 2015 đã mô hình hóa và đo đạc đầy đủ ma sát tiếp xúc giữa các dây NiTi.",
            "inferred_conclusions": "Không thể tuyên bố tính mới về mặt hiện tượng ma sát dây NiTi đơn thuần.",
            "unresolved_issues": "Sự phụ thuộc của hệ số ma sát $\mu$ vào trạng thái pha (Austenite vs Martensite) và ứng suất tiếp xúc pháp tuyến lớn.",
            "later_critique_ids": ["G05", "G06"],
            "later_remediation_ids": ["W04"],
            "superseded_interpretation": "Nghi ngờ ma sát tiếp xúc giữa các dây NiTi chưa được nghiên cứu trong cơ học.",
            "corrected_interpretation": "Xác nhận T1 đã đóng hoàn toàn; loại bỏ T1 khỏi danh mục các khoảng trống mở.",
            "evidence_status": "closed_by_full_text",
            "confidence": "high",
            "provenance": "W06_T1_NITI_CONTACT_FRICTION.md#L1-L339"
        },
        {
            "packet_id": "W07",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W07_T2_ACTIVE_CONFINEMENT_PRESSURE.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra ranh giới Mục tiêu T2: Áp suất giam giữ chủ động (Active Confinement Pressure) và sự phân loại P1/P2/P3.",
            "claims_affected": ["C6"],
            "targets_affected": ["T2"],
            "hypotheses_affected": ["H0b", "H1"],
            "papers_used": ["ccdc1bb980", "aaad9c248c", "53200aa0c6", "fac21c950e"],
            "method_or_model": "Lý thuyết uốn dầm cáp dưới áp suất ngoài; phân loại áp suất P1 (tiếp xúc thụ động do hình học), P2 (áp suất cố định/thủy tĩnh), P3 (áp suất chủ động biến thiên $p(t)$).",
            "experiment_discussed": "Cáp ngầm biển chịu áp suất thủy tĩnh (Tjahjanto 2017); cáp chịu kéo dọc trục sinh lực nén hướng tâm (Xin Liu 2004).",
            "verified_conclusions": "T2 mở trong tập tài liệu toàn văn hiện tại (open in current full-text set). Các nghiên cứu truyền thống chỉ xét P1 và P2, chưa nghiên cứu sâu P3 trong dầm uốn biến dạng lớn.",
            "inferred_conclusions": "Xem P3 như một lớp cơ học mới có khả năng tạo ra tính mới khoa học độc lập.",
            "unresolved_issues": "P3 là một quy luật cơ học mới hay thực chất chỉ là một điều kiện biên biến thiên theo thời gian trong phương trình vi phân tiếp xúc hiện hữu.",
            "later_critique_ids": ["G02", "G09", "G10"],
            "later_remediation_ids": ["W05", "W08"],
            "superseded_interpretation": "Nhận định áp suất chủ động P3 tạo ra một nhánh cơ học mới chưa từng có phương trình.",
            "corrected_interpretation": "Hạ cấp P3 thành giao thức điều khiển thực nghiệm (experimental protocol/boundary condition); phương trình vi phân hiện hữu tiếp nhận tự nhiên $p(t)$.",
            "evidence_status": "open_in_current_full_text_set",
            "confidence": "medium",
            "provenance": "W07_T2_ACTIVE_CONFINEMENT_PRESSURE.md#L1-L199"
        },
        {
            "packet_id": "W08",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W08_T3_TRANSFORMATION_CONTACT_COUPLING.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra Mục tiêu T3: Sự ghép cặp chuyển pha và tiếp xúc ma sát dây NiTi; kiểm tra mức độ đón đầu của văn hiến.",
            "claims_affected": ["C7"],
            "targets_affected": ["T3"],
            "hypotheses_affected": ["H0b", "H1"],
            "papers_used": ["d9966f2f5e", "53200aa0c6", "98fee47c04", "e8462758c3", "6dd1ca94d1"],
            "method_or_model": "Mô hình cấu thành nhiệt-cơ ghép cặp tiếp xúc; mô hình trễ thắt (pinched hysteresis) kết hợp siêu đàn hồi và ma sát Bouc-Wen.",
            "experiment_discussed": "Thử nghiệm uốn và kéo chu kỳ trên tao dây cáp; quan sát hiện tượng suy giảm chu kỳ và trễ năng lượng.",
            "verified_conclusions": "Mục tiêu T3 bị đón đầu thực chất (substantially preempted). Các mô hình ghép cặp siêu đàn hồi và ma sát đã được nghiên cứu sâu trong giảm chấn công trình và hàng không.",
            "inferred_conclusions": "Gán nhầm rằng cấu hình S2a của Carboni 2015 chứng minh chuyển pha siêu đàn hồi trong uốn thuần.",
            "unresolved_issues": "Sai sót dữ liệu thực tế: Cấu hình S2a trong Carboni 2015 thực chất là cáp thép thuần ma sát ST49; S1a mới là cáp NiTi chịu kéo-uốn kết hợp.",
            "later_critique_ids": ["G03", "G05", "G11"],
            "later_remediation_ids": ["W04", "W06", "W07"],
            "superseded_interpretation": "Sử dụng S2a làm bằng chứng cho rằng chuyển pha uốn thuần đã được thực nghiệm chứng minh.",
            "corrected_interpretation": "Đính chính triệt để sai sót S2a; chỉ ra rằng Carboni 2015 chỉ thử nghiệm kéo-uốn kết hợp trên S1a, chưa chứng minh uốn thuần.",
            "evidence_status": "substantially_preempted",
            "confidence": "medium_low",
            "provenance": "W08_T3_TRANSFORMATION_CONTACT_COUPLING.md#L1-L157"
        },
        {
            "packet_id": "W09",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W09_REEDLUNN_2013_DEEP_AUDIT.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra toàn văn chuyên sâu Reedlunn et al. 2013 (Part II), phân tích cơ chế chuyển pha từng lớp và giới hạn động học Costello.",
            "claims_affected": ["C7"],
            "targets_affected": ["T1", "T3"],
            "hypotheses_affected": ["H0b", "H1"],
            "papers_used": ["fac21c950e"],
            "method_or_model": "Lý thuyết cáp xoắn Costello kết hợp luật cấu thành siêu đàn hồi 1D có biến dạng trượt xuyên tâm và đo quang học.",
            "experiment_discussed": "Kéo đẳng nhiệt cáp $7\\times 7$ và $1\\times 27$ NiTi trong bể chất lỏng kiểm soát nhiệt độ; chụp ảnh bề mặt xác định vùng chuyển pha.",
            "verified_conclusions": "Reedlunn 2013 chứng minh quá trình chuyển pha diễn ra tuần tự từng lớp từ trong ra ngoài; cho thấy áp lực tiếp xúc hướng tâm làm thay đổi ứng suất kích hoạt chuyển pha.",
            "inferred_conclusions": "Cho rằng việc mô hình Costello thất bại ở lớp ngoài cáp $1\\times 27$ chứng minh sự thiếu hụt của lý thuyết tiếp xúc-chuyển pha tổng quát.",
            "unresolved_issues": "Diễn giải quá mức (overclaim) sai số động học cáp xoắn dốc Costello thành sự thất bại của luật cấu thành trong bó dây robot thẳng.",
            "later_critique_ids": ["G07"],
            "later_remediation_ids": ["W10"],
            "superseded_interpretation": "Dùng sự sai lệch của mô hình Costello trong Reedlunn để làm căn cứ khẳng định cần một phương trình ghép cặp mới.",
            "corrected_interpretation": "Thừa nhận sự sai lệch của Reedlunn thuần túy do giả thiết động học thanh xoắn góc lớn bỏ qua uốn/xoắn cục bộ; không suy diễn cho bó dây thẳng.",
            "evidence_status": "closed_for_axial_cable_kinematics",
            "confidence": "high",
            "provenance": "W09_REEDLUNN_2013_DEEP_AUDIT.md#L1-L146"
        },
        {
            "packet_id": "W10",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W10_FANG_2019_PARAMETER_SUBSTITUTION.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra sâu Fang et al. 2019 và đánh giá rủi ro của phép thử thay thế tham số (parameter-substitution risk).",
            "claims_affected": ["C7"],
            "targets_affected": ["T3"],
            "hypotheses_affected": ["H0a", "H0b", "H1"],
            "papers_used": ["2f7fcf2f8f"],
            "method_or_model": "Phần tử thanh dầm OpenSees với mặt cắt sợi siêu đàn hồi và lò xo phi tuyến tự định tâm song song; mô hình suy giảm chu kỳ.",
            "experiment_discussed": "Kéo chu kỳ và uốn-cắt trên cơ cấu giảm chấn cáp NiTi; khớp đường cong trễ dạng cờ và sự trơn mượt chuyển pha.",
            "verified_conclusions": "Mô hình rút gọn của Fang 2019 tái hiện rất tốt hình dạng đường cong trễ vĩ mô bằng cách tinh chỉnh tham số hiện tượng học mà không cần giải phương trình tiếp xúc vi mô.",
            "inferred_conclusions": "Rủi ro thay thế tham số là cực kỳ nghiêm trọng: một mô hình hiện tượng học hiện có có thể khớp đường cong mà không cần lý thuyết mới.",
            "unresolved_issues": "Phép khớp đường cong vĩ mô không chứng minh được tính nhân quả vật lý; hiện tượng bù trừ giữa ma sát và độ cứng.",
            "later_critique_ids": ["G06", "G08", "G10"],
            "later_remediation_ids": ["W07", "W09", "W10"],
            "superseded_interpretation": "Coi kết quả kiểm tra thay thế tham số là chưa kết luận dứt điểm (insufficient).",
            "corrected_interpretation": "Xác nhận H0b (mô hình phi tuyến hiện có) chưa bị bác bỏ; các mô hình hiện tượng học khớp số liệu rất tốt; H1 đòi hỏi bằng chứng nhân quả cục bộ.",
            "evidence_status": "parameter_substitution_risk_high",
            "confidence": "high",
            "provenance": "W10_FANG_2019_PARAMETER_SUBSTITUTION.md#L1-L149"
        },
        {
            "packet_id": "W11",
            "packet_file": "outputs/reports/MP1_MECHANICS_TRACE_PACKETS_2026-09-25/W11_CITATION_COVERAGE_AND_SOURCE_INTEGRITY.md",
            "repository_commit": "af9e7a5",
            "historical_stage": "Stage 1 (Mechanics Trace Packets)",
            "question_answered": "Thẩm tra độ bao phủ trích dẫn và tính toàn vẹn của cơ sở dữ liệu nguồn, đánh giá điều kiện dừng tìm kiếm.",
            "claims_affected": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8"],
            "targets_affected": ["T1", "T2", "T3"],
            "hypotheses_affected": ["H0a", "H0b", "H1"],
            "papers_used": ["00414aac4b", "fac21c950e", "40760daa02", "2f7fcf2f8f", "7f3f45407f", "1c81b2d35c", "9f4295be23", "56793dea9b", "d9966f2f5e", "9e15094d68", "53200aa0c6", "98fee47c04", "aaad9c248c", "ccdc1bb980", "e8462758c3", "6dd1ca94d1"],
            "method_or_model": "Kiểm toán đồ thị trích dẫn ngược (B01-B08/B12) và trích dẫn xuôi (F01-F06); sàng lọc 178 ứng viên theo tiêu chí bao gồm/loại trừ.",
            "experiment_discussed": "Đối soát số lượng bài báo toàn văn (10 vs 13 vs 16) và trạng thái dừng trích dẫn trên ma trận kiểm chứng.",
            "verified_conclusions": "Đã sàng lọc 178 ứng viên; 16 bài báo toàn văn chính tắc; điều kiện dừng chưa đạt (`stop_condition_satisfied = false`); ngày cắt tìm kiếm chưa thiết lập.",
            "inferred_conclusions": "Không tìm thấy bài báo trong tập 178 bài không tương đương với việc bài toán chưa từng được giải trong toàn bộ nền khoa học.",
            "unresolved_issues": "Xung đột giữa việc tuyên bố 'đã xác lập khoảng trống' trong báo cáo và cờ `stop_condition_satisfied = false` trong registry.",
            "later_critique_ids": ["G10", "G11"],
            "later_remediation_ids": ["W01", "W11"],
            "superseded_interpretation": "Từng kết luận như thể khoảng trống cơ học đã được xác lập chắc chắn 100%.",
            "corrected_interpretation": "Minh bạch hóa rằng khoảng trống chỉ là một giả thuyết còn sống sót tạm thời (PROVISIONALLY SURVIVING HYPOTHESIS).",
            "evidence_status": "stop_condition_unmet",
            "confidence": "high",
            "provenance": "W11_CITATION_COVERAGE_AND_SOURCE_INTEGRITY.md#L1-L218"
        }
    ]

print("Stage 1 packets defined: 11")
